name: Test Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print current branch
        run: echo "Branch: ${{ github.ref }}"

      - name: Run basic check
        run: |
          if [[ $(grep -i "error" README.md) ]]; then
            echo "❌ Found 'error' in README.md"
            exit 1
          else
            echo "✅ README.md looks good"
          fi

      - name: Custom Step - just printing
        run: echo "This is an extra custom step"
